service: forge-serverless-api

package:
  individually: true

plugins:
  - serverless-bundle 
  - serverless-offline
  - serverless-dotenv-plugin 

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  environment:
    clientID: ${env:CLIENT_ID}
    clientSecret: ${env:CLIENT_SECRET}
    callbackURL: ${env:CALLBACK_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-2:*:*"

functions:
  create_session:
    handler: functions/oauth.create_session
    events:
      - http:
          path: oauth/create_session
          method: get
  get_user_profile:
    handler: functions/user.profile
    events:
      - http:
          path: user/profile
          method: get
  get_docs:
    handler: functions/datamanagement.datamanagement
    events:
      - http:
          path: datamanagement
          method: get
  get_asset:
    handler: functions/disciplines/get_asset.get_asset
    events:
      - http:
          path: assets/{asset_id}
          method: get
          cors: true
  add_note:
    handler: functions/disciplines/add_note.add_note
    events:
      - http:
          path: add_note
          method: post
          cors: true